name: 编译 OpenWrt 固件

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "选择源分支"
        required: true
        default: "openwrt-main"
        type: choice
        options:
          - openwrt-main
          - immortalwrt-master
      version:
        description: "指定版本（标签），留空则使用最新分支"
        required: false
      openwrt_board:
        description: "选择设备板卡"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - wr30u-stock
          - wr30u-ubootmod
          - wr30u-112m-nmbm
          - cr6608

jobs:
  build:
    runs-on: ubuntu-24.04  # 使用 Ubuntu 24.04 LTS

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 初始化环境
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: 确定仓库和分支
        id: determine_repo
        run: |
          if [ "${{ inputs.source_branch }}" = "openwrt-main" ]; then
            echo "REPO=https://github.com/openwrt/openwrt.git" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
          elif [ "${{ inputs.source_branch }}" = "immortalwrt-master" ]; then
            echo "REPO=https://github.com/immortalwrt/immortalwrt.git" >> $GITHUB_ENV
            echo "BRANCH=master" >> $GITHUB_ENV
          fi

      - name: 克隆源代码
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            git clone -b ${{ inputs.version }} $REPO openwrt
          else
            git clone -b $BRANCH $REPO openwrt
          fi

      - name: 更新 Feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 确定构建配置
        id: determine_build
        run: |
          if [ "${{ inputs.openwrt_board }}" = "all" ]; then
            echo "BUILD_TARGETS=mediatek_filogic ramips_mt7621" >> $GITHUB_ENV
            echo "BUILD_PROFILES_mediatenk_filogic=wr30u-stock wr30u-ubootmod wr30u-112m-nmbm" >> $GITHUB_ENV
            echo "BUILD_PROFILES_ramips_mt7621=cr6608" >> $GITHUB_ENV
          else
            case ${{ inputs.openwrt_board }} in
              wr30u-stock|wr30u-ubootmod|wr30u-112m-nmbm)
                echo "BUILD_TARGETS=mediatek_filogic" >> $GITHUB_ENV
                echo "BUILD_PROFILES_mediatenk_filogic=${{ inputs.openwrt_board }}" >> $GITHUB_ENV
                ;;
              cr6608)
                echo "BUILD_TARGETS=ramips_mt7621" >> $GITHUB_ENV
                echo "BUILD_PROFILES_ramips_mt7621=cr6608" >> $GITHUB_ENV
                ;;
            esac
          fi

      - name: 构建 OpenWrt
        working-directory: openwrt
        run: |
          mkdir -p output
          for target in $BUILD_TARGETS; do
            make_target=${target//_/ /}
            make defconfig TARGET=$make_target
            make
            profiles_var="BUILD_PROFILES_$target"
            for profile in ${!profiles_var}; do
              make image PROFILE=$profile
              profile_dir="bin/targets/$make_target/*/$profile"
              output_dir="output/$target/$profile"
              mkdir -p "$output_dir"
              [ -d "$profile_dir" ] && cp "$profile_dir/"openwrt*" "$output_dir/"
            done
          done

      - name: 上传构建结果
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-images
          path: openwrt/output/*
