name: Build OpenWrt/ImmortalWrt Firmware

on:
  workflow_dispatch:
    inputs:
      firmware:
        description: '选择固件 (openwrt-main, immortalwrt-master, all)'
        required: true
        default: 'all'
        type: choice
        options:
          - openwrt-main
          - immortalwrt-master
          - all
      device:
        description: '选择设备型号 (xiaomi_mi-router-wr30u-stock, xiaomi_mi-router-wr30u-ubootmod, xiaomi_mi-router-wr30u-112m-nmbm, xiaomi_mi-router-cr6608, all)'
        required: true
        default: 'all'
        type: choice
        options:
          - xiaomi_mi-router-wr30u-stock
          - xiaomi_mi-router-wr30u-ubootmod
          - xiaomi_mi-router-wr30u-112m-nmbm
          - xiaomi_mi-router-cr6608
          - all
      version:
        description: '选择固件版本（留空使用最新版本）'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    
      # 第一步：设置环境
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      # 第二步：选择版本
      - name: Checkout openwrt/immortalwrt repository
        run: |
          if [ "${{ github.event.inputs.firmware }}" == "openwrt-main" ]; then
            echo "Checking out openwrt-main"
            git clone --branch master https://github.com/openwrt/openwrt.git
          elif [ "${{ github.event.inputs.firmware }}" == "immortalwrt-master" ]; then
            echo "Checking out immortalwrt-master"
            git clone --branch master https://github.com/immortalwrt/immortalwrt.git
          elif [ "${{ github.event.inputs.firmware }}" == "all" ]; then
            echo "Cloning both OpenWrt and ImmortalWrt repositories"
            git clone --branch master https://github.com/openwrt/openwrt.git
            git clone --branch master https://github.com/immortalwrt/immortalwrt.git
          fi

      # 第三步：选择设备型号
      - name: Select device configuration
        run: |
          if [ "${{ github.event.inputs.device }}" == "xiaomi_mi-router-wr30u-stock" ]; then
            CONFIG="xiaomi_mi-router-wr30u-stock"
          elif [ "${{ github.event.inputs.device }}" == "xiaomi_mi-router-wr30u-ubootmod" ]; then
            CONFIG="xiaomi_mi-router-wr30u-ubootmod"
          elif [ "${{ github.event.inputs.device }}" == "xiaomi_mi-router-wr30u-112m-nmbm" ]; then
            CONFIG="xiaomi_mi-router-wr30u-112m-nmbm"
          elif [ "${{ github.event.inputs.device }}" == "xiaomi_mi-router-cr6608" ]; then
            CONFIG="xiaomi_mi-router-cr6608"
          else
            CONFIG="all"
          fi
          echo "Selected device: ${CONFIG}"

      # 第四步：选择版本
      - name: Check version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "No version specified, using latest version"
            VERSION="latest"
          else
            echo "Using specified version: ${{ github.event.inputs.version }}"
            VERSION="${{ github.event.inputs.version }}"
          fi

      # 第五步：配置编译环境和固件
      - name: Configure firmware
        run: |
          if [ "${{ github.event.inputs.firmware }}" == "openwrt-main" ] || [ "${{ github.event.inputs.firmware }}" == "all" ]; then
            cd openwrt
            if [ "${VERSION}" != "latest" ]; then
              git checkout ${VERSION}
            fi
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make menuconfig
            make defconfig
            # 保存配置文件
            mkdir -p config/openwrt-main/${CONFIG}
            cp .config config/openwrt-main/${CONFIG}/config
            cd ..
          fi
          
          if [ "${{ github.event.inputs.firmware }}" == "immortalwrt-master" ] || [ "${{ github.event.inputs.firmware }}" == "all" ]; then
            cd immortalwrt
            if [ "${VERSION}" != "latest" ]; then
              git checkout ${VERSION}
            fi
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make menuconfig
            make defconfig
            # 保存配置文件
            mkdir -p config/immortalwrt-master/${CONFIG}
            cp .config config/immortalwrt-master/${CONFIG}/config
            cd ..
          fi

      # 第六步：编译固件
      - name: Build firmware
        run: |
          if [ "${{ github.event.inputs.firmware }}" == "openwrt-main" ] || [ "${{ github.event.inputs.firmware }}" == "all" ]; then
            cd openwrt
            make -j$(nproc)
            cd ..
          fi
          
          if [ "${{ github.event.inputs.firmware }}" == "immortalwrt-master" ] || [ "${{ github.event.inputs.firmware }}" == "all" ]; then
            cd immortalwrt
            make -j$(nproc)
            cd ..
          fi
