name: Build OpenWrt Config

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装依赖
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

    # 设置 OpenWrt 环境
    - name: Setup OpenWrt environment
      run: |
        # 更新 feeds
        cd openwrt/ && ./scripts/feeds update -a
        cd openwrt/ && ./scripts/feeds install -a

    # 运行 make defconfig
    - name: Generate .config
      run: |
        make defconfig
        mv .config openwrt-config-$(date +%Y%m%d).config

    # 上传 .config 文件到 Artifacts
    - name: Upload .config as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-config
        path: openwrt-config-*.config

    # 创建 Release 并上传 .config
    - name: Create Release and Upload Config
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push'  # 仅在 push 时创建 Release
      with:
        tag_name: config-$(date +%Y%m%d)
        name: OpenWrt Config $(date +%Y%m%d)
        body: Auto-generated OpenWrt .config file
        files: openwrt-config-*.config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
